/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidjni_MainActivity */

#ifndef _Included_com_example_androidjni_MainActivity
#define _Included_com_example_androidjni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidjni_MainActivity
 * Method:    getJniData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jobject JNICALL Java_com_example_androidjni_MainActivity_getJniData
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
